[2023-10-19T13:22:14.314+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_notification.get_stock_price manual__2023-10-19T13:22:09.955411+00:00 [queued]>
[2023-10-19T13:22:14.325+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_notification.get_stock_price manual__2023-10-19T13:22:09.955411+00:00 [queued]>
[2023-10-19T13:22:14.325+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-10-19T13:22:14.335+0000] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): get_stock_price> on 2023-10-19 13:22:09.955411+00:00
[2023-10-19T13:22:14.362+0000] {standard_task_runner.py:57} INFO - Started process 2997 to run task
[2023-10-19T13:22:14.366+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stock_notification', 'get_stock_price', 'manual__2023-10-19T13:22:09.955411+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/stock_notification.py', '--cfg-path', '/tmp/tmpq1wn6bv3']
[2023-10-19T13:22:14.371+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask get_stock_price
[2023-10-19T13:22:14.432+0000] {task_command.py:416} INFO - Running <TaskInstance: stock_notification.get_stock_price manual__2023-10-19T13:22:09.955411+00:00 [running]> on host 46830eaaaf4f
[2023-10-19T13:22:14.908+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='joshua881117@gmail.com' AIRFLOW_CTX_DAG_OWNER='Joshua Lin' AIRFLOW_CTX_DAG_ID='stock_notification' AIRFLOW_CTX_TASK_ID='get_stock_price' AIRFLOW_CTX_EXECUTION_DATE='2023-10-19T13:22:09.955411+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-19T13:22:09.955411+00:00'
[2023-10-19T13:22:14.911+0000] {log.py:232} WARNING - 2023-10-19 13:22:14.910 | INFO     | stock_app.stock_crawler:crawler_twse:198 - crawler_twse
[2023-10-19T13:22:22.330+0000] {log.py:232} WARNING - 2023-10-19 13:22:22.329 | INFO     | stock_app.stock_crawler:convert_change:254 - convert_change
[2023-10-19T13:22:22.965+0000] {logging_mixin.py:151} INFO - /opt/***/dags
[2023-10-19T13:22:22.969+0000] {logging_mixin.py:151} INFO - /opt/***/dags/data/stock_data.csv
[2023-10-19T13:22:23.222+0000] {python.py:194} INFO - Done. Returned value was: compare_price
[2023-10-19T13:22:23.224+0000] {python.py:227} INFO - Branch callable return compare_price
[2023-10-19T13:22:23.225+0000] {skipmixin.py:173} INFO - Following branch compare_price
[2023-10-19T13:22:23.304+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 228, in execute
    self.skip_all_except(context["ti"], branch)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/skipmixin.py", line 208, in skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'compare_price'}.
[2023-10-19T13:22:23.317+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_notification, task_id=get_stock_price, execution_date=20231019T132209, start_date=20231019T132214, end_date=20231019T132223
[2023-10-19T13:22:23.409+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-10-19T13:22:23.410+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2023-10-19T13:22:23.411+0000] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-19T13:22:23.431+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2023-10-19T13:22:23.431+0000] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-19T13:22:23.432+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['joshua881117@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 228, in execute
    self.skip_all_except(context["ti"], branch)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/skipmixin.py", line 208, in skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'compare_price'}.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-10-19T13:22:23.466+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 37 for task get_stock_price ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'compare_price'}.; 2997)
[2023-10-19T13:22:23.504+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-19T13:22:23.577+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
