[2023-10-23T21:21:26.530+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_data_crawler.upload_to_db manual__2023-10-23T12:51:29.324312+00:00 [queued]>
[2023-10-23T21:21:26.535+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_data_crawler.upload_to_db manual__2023-10-23T12:51:29.324312+00:00 [queued]>
[2023-10-23T21:21:26.535+0800] {taskinstance.py:1361} INFO - Starting attempt 6 of 7
[2023-10-23T21:21:26.544+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_to_db> on 2023-10-23 12:51:29.324312+00:00
[2023-10-23T21:21:26.549+0800] {standard_task_runner.py:57} INFO - Started process 1132 to run task
[2023-10-23T21:21:26.552+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stock_data_crawler', 'upload_to_db', 'manual__2023-10-23T12:51:29.324312+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_crawler.py', '--cfg-path', '/tmp/tmprs8sgryu']
[2023-10-23T21:21:26.554+0800] {standard_task_runner.py:85} INFO - Job 119: Subtask upload_to_db
[2023-10-23T21:21:26.595+0800] {task_command.py:416} INFO - Running <TaskInstance: stock_data_crawler.upload_to_db manual__2023-10-23T12:51:29.324312+00:00 [running]> on host 548759eac962
[2023-10-23T21:21:26.636+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='joshua881117@gmail.com' AIRFLOW_CTX_DAG_OWNER='Joshua Lin' AIRFLOW_CTX_DAG_ID='stock_data_crawler' AIRFLOW_CTX_TASK_ID='upload_to_db' AIRFLOW_CTX_EXECUTION_DATE='2023-10-23T12:51:29.324312+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-23T12:51:29.324312+00:00'
[2023-10-23T21:21:27.686+0800] {logging_mixin.py:151} INFO - mysql+pymysql://root:test@mysql:3306/financialdata
[2023-10-23T21:21:27.687+0800] {logging_mixin.py:151} INFO - <class 'sqlalchemy.engine.base.Engine'>
[2023-10-23T21:21:28.723+0800] {logging_mixin.py:151} INFO - mysql+pymysql://root:test@mysql:3306/financialdata
[2023-10-23T21:21:28.737+0800] {logging_mixin.py:151} INFO - <class 'sqlalchemy.engine.base.Engine'>
[2023-10-23T21:21:29.789+0800] {logging_mixin.py:151} INFO - mysql+pymysql://root:test@mysql:3306/financialdata
[2023-10-23T21:21:29.793+0800] {logging_mixin.py:151} INFO - <class 'sqlalchemy.engine.base.Engine'>
[2023-10-23T21:21:30.824+0800] {logging_mixin.py:151} INFO - mysql+pymysql://root:test@mysql:3306/financialdata
[2023-10-23T21:21:30.826+0800] {logging_mixin.py:151} INFO - <class 'sqlalchemy.engine.base.Engine'>
[2023-10-23T21:21:31.860+0800] {logging_mixin.py:151} INFO - mysql+pymysql://root:test@mysql:3306/financialdata
[2023-10-23T21:21:31.867+0800] {logging_mixin.py:151} INFO - <class 'sqlalchemy.engine.base.Engine'>
[2023-10-23T21:21:31.886+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stock_data_crawler.py", line 47, in upload_data
    with r.mysql_conn as conn:
AttributeError: __enter__
[2023-10-23T21:21:31.898+0800] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_data_crawler, task_id=upload_to_db, execution_date=20231023T125129, start_date=20231023T132126, end_date=20231023T132131
[2023-10-23T21:21:31.959+0800] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-10-23T21:21:31.961+0800] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-23T21:21:33.856+0800] {email.py:281} INFO - Sent an alert email to ['joshua881117@gmail.com']
[2023-10-23T21:21:35.297+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 119 for task upload_to_db (__enter__; 1132)
[2023-10-23T21:21:35.338+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-23T21:21:35.369+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
