[2023-10-23T21:26:33.082+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_data_crawler.upload_to_db manual__2023-10-23T12:51:29.324312+00:00 [queued]>
[2023-10-23T21:26:33.088+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_data_crawler.upload_to_db manual__2023-10-23T12:51:29.324312+00:00 [queued]>
[2023-10-23T21:26:33.088+0800] {taskinstance.py:1361} INFO - Starting attempt 7 of 7
[2023-10-23T21:26:33.096+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_to_db> on 2023-10-23 12:51:29.324312+00:00
[2023-10-23T21:26:33.101+0800] {standard_task_runner.py:57} INFO - Started process 1327 to run task
[2023-10-23T21:26:33.104+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stock_data_crawler', 'upload_to_db', 'manual__2023-10-23T12:51:29.324312+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_crawler.py', '--cfg-path', '/tmp/tmpf11n37bs']
[2023-10-23T21:26:33.106+0800] {standard_task_runner.py:85} INFO - Job 120: Subtask upload_to_db
[2023-10-23T21:26:33.130+0800] {task_command.py:416} INFO - Running <TaskInstance: stock_data_crawler.upload_to_db manual__2023-10-23T12:51:29.324312+00:00 [running]> on host 548759eac962
[2023-10-23T21:26:33.162+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='joshua881117@gmail.com' AIRFLOW_CTX_DAG_OWNER='Joshua Lin' AIRFLOW_CTX_DAG_ID='stock_data_crawler' AIRFLOW_CTX_TASK_ID='upload_to_db' AIRFLOW_CTX_EXECUTION_DATE='2023-10-23T12:51:29.324312+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-23T12:51:29.324312+00:00'
[2023-10-23T21:26:34.226+0800] {logging_mixin.py:151} INFO - mysql+pymysql://root:test@mysql:3306/financialdata
[2023-10-23T21:26:34.229+0800] {logging_mixin.py:151} INFO - <class 'sqlalchemy.engine.base.Engine'>
[2023-10-23T21:26:35.260+0800] {logging_mixin.py:151} INFO - mysql+pymysql://root:test@mysql:3306/financialdata
[2023-10-23T21:26:35.262+0800] {logging_mixin.py:151} INFO - <class 'sqlalchemy.engine.base.Engine'>
[2023-10-23T21:26:36.319+0800] {logging_mixin.py:151} INFO - mysql+pymysql://root:test@mysql:3306/financialdata
[2023-10-23T21:26:36.323+0800] {logging_mixin.py:151} INFO - <class 'sqlalchemy.engine.base.Engine'>
[2023-10-23T21:26:37.370+0800] {logging_mixin.py:151} INFO - mysql+pymysql://root:test@mysql:3306/financialdata
[2023-10-23T21:26:37.372+0800] {logging_mixin.py:151} INFO - <class 'sqlalchemy.engine.base.Engine'>
[2023-10-23T21:26:38.382+0800] {logging_mixin.py:151} INFO - mysql+pymysql://root:test@mysql:3306/financialdata
[2023-10-23T21:26:38.383+0800] {logging_mixin.py:151} INFO - <class 'sqlalchemy.engine.base.Engine'>
[2023-10-23T21:26:38.392+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stock_data_crawler.py", line 47, in upload_data
    with r.mysql_conn as conn:
AttributeError: __enter__
[2023-10-23T21:26:38.405+0800] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=stock_data_crawler, task_id=upload_to_db, execution_date=20231023T125129, start_date=20231023T132633, end_date=20231023T132638
[2023-10-23T21:26:38.444+0800] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-10-23T21:26:38.444+0800] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-23T21:26:40.345+0800] {email.py:281} INFO - Sent an alert email to ['joshua881117@gmail.com']
[2023-10-23T21:26:41.607+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 120 for task upload_to_db (__enter__; 1327)
[2023-10-23T21:26:41.643+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-23T21:26:41.664+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
