[2023-10-25T20:34:15.157+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_data_crawler.get_stock_data scheduled__2023-10-24T10:00:00+00:00 [queued]>
[2023-10-25T20:34:15.163+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_data_crawler.get_stock_data scheduled__2023-10-24T10:00:00+00:00 [queued]>
[2023-10-25T20:34:15.163+0800] {taskinstance.py:1361} INFO - Starting attempt 5 of 6
[2023-10-25T20:34:15.171+0800] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): get_stock_data> on 2023-10-24 10:00:00+00:00
[2023-10-25T20:34:15.177+0800] {standard_task_runner.py:57} INFO - Started process 3905 to run task
[2023-10-25T20:34:15.180+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stock_data_crawler', 'get_stock_data', 'scheduled__2023-10-24T10:00:00+00:00', '--job-id', '453', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_crawler.py', '--cfg-path', '/tmp/tmp8os77lgm']
[2023-10-25T20:34:15.186+0800] {standard_task_runner.py:85} INFO - Job 453: Subtask get_stock_data
[2023-10-25T20:34:15.222+0800] {task_command.py:416} INFO - Running <TaskInstance: stock_data_crawler.get_stock_data scheduled__2023-10-24T10:00:00+00:00 [running]> on host bb5c9ebbc514
[2023-10-25T20:34:15.273+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='joshua881117@gmail.com' AIRFLOW_CTX_DAG_OWNER='Joshua Lin' AIRFLOW_CTX_DAG_ID='stock_data_crawler' AIRFLOW_CTX_TASK_ID='get_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-24T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-24T10:00:00+00:00'
[2023-10-25T20:34:15.274+0800] {logging_mixin.py:151} INFO - 2023-10-24 10:00:00+00:00
[2023-10-25T20:34:15.275+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 226, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stock_data_crawler.py", line 29, in get_data
    df = crawler_twse(date)
  File "/opt/airflow/dags/functions/crawler/stock_crawler.py", line 202, in crawler_twse
    date=date.replace("-", "")
TypeError: an integer is required (got type str)
[2023-10-25T20:34:15.281+0800] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_data_crawler, task_id=get_stock_data, execution_date=20231024T100000, start_date=20231025T123415, end_date=20231025T123415
[2023-10-25T20:34:15.295+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 453 for task get_stock_data (an integer is required (got type str); 3905)
[2023-10-25T20:34:15.312+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-25T20:34:15.327+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
