[2023-10-25T16:18:19.091+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_data_crawler.get_stock_data manual__2023-10-25T16:13:13+08:00 [queued]>
[2023-10-25T16:18:19.105+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_data_crawler.get_stock_data manual__2023-10-25T16:13:13+08:00 [queued]>
[2023-10-25T16:18:19.106+0800] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2023-10-25T16:18:19.132+0800] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): get_stock_data> on 2023-10-25 08:13:13+00:00
[2023-10-25T16:18:19.171+0800] {standard_task_runner.py:57} INFO - Started process 6461 to run task
[2023-10-25T16:18:19.182+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stock_data_crawler', 'get_stock_data', 'manual__2023-10-25T16:13:13+08:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_crawler.py', '--cfg-path', '/tmp/tmpddxphknz']
[2023-10-25T16:18:19.186+0800] {standard_task_runner.py:85} INFO - Job 334: Subtask get_stock_data
[2023-10-25T16:18:19.246+0800] {task_command.py:416} INFO - Running <TaskInstance: stock_data_crawler.get_stock_data manual__2023-10-25T16:13:13+08:00 [running]> on host bb5c9ebbc514
[2023-10-25T16:18:19.337+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='joshua881117@gmail.com' AIRFLOW_CTX_DAG_OWNER='Joshua Lin' AIRFLOW_CTX_DAG_ID='stock_data_crawler' AIRFLOW_CTX_TASK_ID='get_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-25T08:13:13+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-25T16:13:13+08:00'
[2023-10-25T16:18:27.528+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 226, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stock_data_crawler.py", line 30, in get_data
    file_dir = os.path.abspath(file_dir, os.pardir)
TypeError: abspath() takes 1 positional argument but 2 were given
[2023-10-25T16:18:27.550+0800] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_data_crawler, task_id=get_stock_data, execution_date=20231025T081313, start_date=20231025T081819, end_date=20231025T081827
[2023-10-25T16:18:27.568+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 334 for task get_stock_data (abspath() takes 1 positional argument but 2 were given; 6461)
[2023-10-25T16:18:27.597+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-25T16:18:27.631+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
