[2023-10-22T16:36:29.763+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_notification.get_target manual__2023-10-22T08:36:16.550560+00:00 [queued]>
[2023-10-22T16:36:29.778+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_notification.get_target manual__2023-10-22T08:36:16.550560+00:00 [queued]>
[2023-10-22T16:36:29.778+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-10-22T16:36:29.787+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_target> on 2023-10-22 08:36:16.550560+00:00
[2023-10-22T16:36:29.804+0800] {standard_task_runner.py:57} INFO - Started process 3492 to run task
[2023-10-22T16:36:29.818+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stock_notification', 'get_target', 'manual__2023-10-22T08:36:16.550560+00:00', '--job-id', '223', '--raw', '--subdir', 'DAGS_FOLDER/stock_notification.py', '--cfg-path', '/tmp/tmpobpxm0xw']
[2023-10-22T16:36:29.823+0800] {standard_task_runner.py:85} INFO - Job 223: Subtask get_target
[2023-10-22T16:36:29.861+0800] {task_command.py:416} INFO - Running <TaskInstance: stock_notification.get_target manual__2023-10-22T08:36:16.550560+00:00 [running]> on host 6a6999315df3
[2023-10-22T16:36:29.898+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='joshua881117@gmail.com' AIRFLOW_CTX_DAG_OWNER='Joshua Lin' AIRFLOW_CTX_DAG_ID='stock_notification' AIRFLOW_CTX_TASK_ID='get_target' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T08:36:16.550560+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T08:36:16.550560+00:00'
[2023-10-22T16:36:29.902+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stock_notification.py", line 42, in get_target_price
    target_df = read_target_stock_sheet(sheet_id, '目標股票')
  File "/opt/airflow/dags/stock_app/stock_functions.py", line 65, in read_target_stock_sheet
    client = connect_to_gsheet()
  File "/opt/airflow/dags/stock_app/stock_functions.py", line 59, in connect_to_gsheet
    credentials = ServiceAccountCredentials.from_json_keyfile_name(creds, scopes)
  File "/home/airflow/.local/lib/python3.8/site-packages/oauth2client/service_account.py", line 219, in from_json_keyfile_name
    with open(filename, 'r') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '{\r\n  "type": "service_account",\r\n  "project_id": "earnest-coder-312212",\r\n  "private_key_id": "b4a1e809fef922a45557c480d8abd8dbdfc409fd",\r\n  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC0ug/dQc6+IxXx\\nnDVSJKImnainGUTotdm7Z4T7yPQF6z+CKRkgls+0pa95WDoRODHVSVscpxICKIyT\\nNqFY7cX6gY+Py0vv8NnfYJlUTURXSOEGVUYCaz5FhEnUdXv8dvytinVht39i6Ooq\\nC+h9ke4Nuk4WFGKSEfQ3mRdUXzzzRMAgL70aEcpIFaxYgC7OxvoTpkiyQSvDV2g7\\nurnC1jA79fSYI7EolpUfTwRXDy0XnVvWjpkhrtO4iSY7HXeearrNs3gLvH9adQqC\\nSHAafGALM5NX6jHt/cC5VZppldE3g7eWavzubLCQ2CTZRDWNPL6f4SveghiKPsIk\\nkfZ/advPAgMBAAECggEATApPO3qBWNndVUOy4aV9Pj8uo2QL7Nf6zRGQz/msxsLE\\n/Wh6ZI5fxTPDQYygHfelbAbJ2aPn/VV/VD9zor2kg7K4qzlP8ZxGp2h3CxPZkdod\\np/MAGmtyD4DKKaTm7oJH7WKo4dz5sa2rPNa20wKwBUGiskKQeMIqHayBtuO9euL4\\nlMGHJMEg/yUivwsA0AyvwyNUi+8NWVRGnURPe66KMoSjYFMVNvY/P98iVA+K3GnV\\nphMk4979K4Y2FAfvXuUL51jR3ImZDfwsruMtkWiyww5KnpiEPHwkRj0heEt3phU8\\nOrmnfDvPAJLEvpWLo5koSfH9uI7mbEpkUMcCyjRzSQKBgQDku6MpsMC+s1zi+wUy\\naudq4BygqT7EzX4nT4WQ8eEBiXI+VLafIWOWpachDo2jRRTCNdWm9juMVTbCaWR8\\nqelUp1q/zGH9Xa2OgATqsJI4nDjkqkaL99pgALGr+eB9ObeAakXdlVodV/XbPgg8\\nr9xo69s2fAtb4lz6KuxmV3XkeQKBgQDKRWVWk2S9IQ1O/xyKrhDePeSh9NbPvD/7\\nHcja9hDAj7hGIw7Xu91x+cG2wXHHlF8ESrabU9566emG4LYcysBwWDQx2+/VncsJ\\n4XvDf9AhK0x+1HRCjb3N8Xo+m8eeM70NTC9Z9V/OVYp7UZBCSkPPmIMqM1QAUex2\\nGmp/gNlghwKBgGK7f+2iB0EJ6UFs+0xNCwF+Jb1P8PFAhoDveYcccXSZYL/5Dy9X\\nWUaQ0LibMJZWXmSKmmPMi93CdrWqip6pNTe+WZTK401bn2wQZI7tkuBuxrwlp/gJ\\nD7E6+3ZxkO5c+JGszeWc714VNuHhP+r6Oljr3h8BomGSL3IpDwwKGrB5AoGBAJzL\\n7MGPIpFl9L4fDo4GXzcYfYp6lKaWRHayYQgzpUrQXkWoWZIspH384Qh9rmjLAFkA\\nXcvM2PMpLokK2sE4/rJX/aYE20cZudIgA+PJyZpcyUCsCq+o1tC1d1DfS3+8lbmg\\nLDis+KanMuFjmdN5ZFWh4VOuVFinKQloctQCGwAzAoGAGrlR7J3O59pfzP1y0IX3\\njKG6GlnxiCAwudw8c9YYsfeI6uihpMkEw3B6PDMU49DrY2rZoiriRGbpL04syySs\\neD3NM+MLwuxPyqw/HR2BrkMoAYXV528pIBXDu10KnntX2uptL6yUlyy47X7wpIjt\\nZIxuh9hCX4XUTTaMzGGSsLk=\\n-----END PRIVATE KEY-----\\n",\r\n  "client_email": "python-gsheet@earnest-coder-312212.iam.gserviceaccount.com",\r\n  "client_id": "114460034961749852195",\r\n  "auth_uri": "https://accounts.google.com/o/oauth2/auth",\r\n  "token_uri": "https://oauth2.googleapis.com/token",\r\n  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",\r\n  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/python-gsheet%40earnest-coder-312212.iam.gserviceaccount.com",\r\n  "universe_domain": "googleapis.com"\r\n}'
[2023-10-22T16:36:29.910+0800] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_notification, task_id=get_target, execution_date=20231022T083616, start_date=20231022T083629, end_date=20231022T083629
[2023-10-22T16:36:29.951+0800] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-10-22T16:36:29.952+0800] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2023-10-22T16:36:29.952+0800] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-22T16:36:29.956+0800] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2023-10-22T16:36:29.956+0800] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-22T16:36:29.957+0800] {taskinstance.py:2007} ERROR - Failed to send email to: ['joshua881117@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stock_notification.py", line 42, in get_target_price
    target_df = read_target_stock_sheet(sheet_id, '目標股票')
  File "/opt/airflow/dags/stock_app/stock_functions.py", line 65, in read_target_stock_sheet
    client = connect_to_gsheet()
  File "/opt/airflow/dags/stock_app/stock_functions.py", line 59, in connect_to_gsheet
    credentials = ServiceAccountCredentials.from_json_keyfile_name(creds, scopes)
  File "/home/airflow/.local/lib/python3.8/site-packages/oauth2client/service_account.py", line 219, in from_json_keyfile_name
    with open(filename, 'r') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '{\r\n  "type": "service_account",\r\n  "project_id": "earnest-coder-312212",\r\n  "private_key_id": "b4a1e809fef922a45557c480d8abd8dbdfc409fd",\r\n  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC0ug/dQc6+IxXx\\nnDVSJKImnainGUTotdm7Z4T7yPQF6z+CKRkgls+0pa95WDoRODHVSVscpxICKIyT\\nNqFY7cX6gY+Py0vv8NnfYJlUTURXSOEGVUYCaz5FhEnUdXv8dvytinVht39i6Ooq\\nC+h9ke4Nuk4WFGKSEfQ3mRdUXzzzRMAgL70aEcpIFaxYgC7OxvoTpkiyQSvDV2g7\\nurnC1jA79fSYI7EolpUfTwRXDy0XnVvWjpkhrtO4iSY7HXeearrNs3gLvH9adQqC\\nSHAafGALM5NX6jHt/cC5VZppldE3g7eWavzubLCQ2CTZRDWNPL6f4SveghiKPsIk\\nkfZ/advPAgMBAAECggEATApPO3qBWNndVUOy4aV9Pj8uo2QL7Nf6zRGQz/msxsLE\\n/Wh6ZI5fxTPDQYygHfelbAbJ2aPn/VV/VD9zor2kg7K4qzlP8ZxGp2h3CxPZkdod\\np/MAGmtyD4DKKaTm7oJH7WKo4dz5sa2rPNa20wKwBUGiskKQeMIqHayBtuO9euL4\\nlMGHJMEg/yUivwsA0AyvwyNUi+8NWVRGnURPe66KMoSjYFMVNvY/P98iVA+K3GnV\\nphMk4979K4Y2FAfvXuUL51jR3ImZDfwsruMtkWiyww5KnpiEPHwkRj0heEt3phU8\\nOrmnfDvPAJLEvpWLo5koSfH9uI7mbEpkUMcCyjRzSQKBgQDku6MpsMC+s1zi+wUy\\naudq4BygqT7EzX4nT4WQ8eEBiXI+VLafIWOWpachDo2jRRTCNdWm9juMVTbCaWR8\\nqelUp1q/zGH9Xa2OgATqsJI4nDjkqkaL99pgALGr+eB9ObeAakXdlVodV/XbPgg8\\nr9xo69s2fAtb4lz6KuxmV3XkeQKBgQDKRWVWk2S9IQ1O/xyKrhDePeSh9NbPvD/7\\nHcja9hDAj7hGIw7Xu91x+cG2wXHHlF8ESrabU9566emG4LYcysBwWDQx2+/VncsJ\\n4XvDf9AhK0x+1HRCjb3N8Xo+m8eeM70NTC9Z9V/OVYp7UZBCSkPPmIMqM1QAUex2\\nGmp/gNlghwKBgGK7f+2iB0EJ6UFs+0xNCwF+Jb1P8PFAhoDveYcccXSZYL/5Dy9X\\nWUaQ0LibMJZWXmSKmmPMi93CdrWqip6pNTe+WZTK401bn2wQZI7tkuBuxrwlp/gJ\\nD7E6+3ZxkO5c+JGszeWc714VNuHhP+r6Oljr3h8BomGSL3IpDwwKGrB5AoGBAJzL\\n7MGPIpFl9L4fDo4GXzcYfYp6lKaWRHayYQgzpUrQXkWoWZIspH384Qh9rmjLAFkA\\nXcvM2PMpLokK2sE4/rJX/aYE20cZudIgA+PJyZpcyUCsCq+o1tC1d1DfS3+8lbmg\\nLDis+KanMuFjmdN5ZFWh4VOuVFinKQloctQCGwAzAoGAGrlR7J3O59pfzP1y0IX3\\njKG6GlnxiCAwudw8c9YYsfeI6uihpMkEw3B6PDMU49DrY2rZoiriRGbpL04syySs\\neD3NM+MLwuxPyqw/HR2BrkMoAYXV528pIBXDu10KnntX2uptL6yUlyy47X7wpIjt\\nZIxuh9hCX4XUTTaMzGGSsLk=\\n-----END PRIVATE KEY-----\\n",\r\n  "client_email": "python-gsheet@earnest-coder-312212.iam.gserviceaccount.com",\r\n  "client_id": "114460034961749852195",\r\n  "auth_uri": "https://accounts.google.com/o/oauth2/auth",\r\n  "token_uri": "https://oauth2.googleapis.com/token",\r\n  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",\r\n  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/python-gsheet%40earnest-coder-312212.iam.gserviceaccount.com",\r\n  "universe_domain": "googleapis.com"\r\n}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-10-22T16:36:29.971+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 223 for task get_target ([Errno 2] No such file or directory: '{\r\n  "type": "service_account",\r\n  "project_id": "earnest-coder-312212",\r\n  "private_key_id": "b4a1e809fef922a45557c480d8abd8dbdfc409fd",\r\n  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC0ug/dQc6+IxXx\\nnDVSJKImnainGUTotdm7Z4T7yPQF6z+CKRkgls+0pa95WDoRODHVSVscpxICKIyT\\nNqFY7cX6gY+Py0vv8NnfYJlUTURXSOEGVUYCaz5FhEnUdXv8dvytinVht39i6Ooq\\nC+h9ke4Nuk4WFGKSEfQ3mRdUXzzzRMAgL70aEcpIFaxYgC7OxvoTpkiyQSvDV2g7\\nurnC1jA79fSYI7EolpUfTwRXDy0XnVvWjpkhrtO4iSY7HXeearrNs3gLvH9adQqC\\nSHAafGALM5NX6jHt/cC5VZppldE3g7eWavzubLCQ2CTZRDWNPL6f4SveghiKPsIk\\nkfZ/advPAgMBAAECggEATApPO3qBWNndVUOy4aV9Pj8uo2QL7Nf6zRGQz/msxsLE\\n/Wh6ZI5fxTPDQYygHfelbAbJ2aPn/VV/VD9zor2kg7K4qzlP8ZxGp2h3CxPZkdod\\np/MAGmtyD4DKKaTm7oJH7WKo4dz5sa2rPNa20wKwBUGiskKQeMIqHayBtuO9euL4\\nlMGHJMEg/yUivwsA0AyvwyNUi+8NWVRGnURPe66KMoSjYFMVNvY/P98iVA+K3GnV\\nphMk4979K4Y2FAfvXuUL51jR3ImZDfwsruMtkWiyww5KnpiEPHwkRj0heEt3phU8\\nOrmnfDvPAJLEvpWLo5koSfH9uI7mbEpkUMcCyjRzSQKBgQDku6MpsMC+s1zi+wUy\\naudq4BygqT7EzX4nT4WQ8eEBiXI+VLafIWOWpachDo2jRRTCNdWm9juMVTbCaWR8\\nqelUp1q/zGH9Xa2OgATqsJI4nDjkqkaL99pgALGr+eB9ObeAakXdlVodV/XbPgg8\\nr9xo69s2fAtb4lz6KuxmV3XkeQKBgQDKRWVWk2S9IQ1O/xyKrhDePeSh9NbPvD/7\\nHcja9hDAj7hGIw7Xu91x+cG2wXHHlF8ESrabU9566emG4LYcysBwWDQx2+/VncsJ\\n4XvDf9AhK0x+1HRCjb3N8Xo+m8eeM70NTC9Z9V/OVYp7UZBCSkPPmIMqM1QAUex2\\nGmp/gNlghwKBgGK7f+2iB0EJ6UFs+0xNCwF+Jb1P8PFAhoDveYcccXSZYL/5Dy9X\\nWUaQ0LibMJZWXmSKmmPMi93CdrWqip6pNTe+WZTK401bn2wQZI7tkuBuxrwlp/gJ\\nD7E6+3ZxkO5c+JGszeWc714VNuHhP+r6Oljr3h8BomGSL3IpDwwKGrB5AoGBAJzL\\n7MGPIpFl9L4fDo4GXzcYfYp6lKaWRHayYQgzpUrQXkWoWZIspH384Qh9rmjLAFkA\\nXcvM2PMpLokK2sE4/rJX/aYE20cZudIgA+PJyZpcyUCsCq+o1tC1d1DfS3+8lbmg\\nLDis+KanMuFjmdN5ZFWh4VOuVFinKQloctQCGwAzAoGAGrlR7J3O59pfzP1y0IX3\\njKG6GlnxiCAwudw8c9YYsfeI6uihpMkEw3B6PDMU49DrY2rZoiriRGbpL04syySs\\neD3NM+MLwuxPyqw/HR2BrkMoAYXV528pIBXDu10KnntX2uptL6yUlyy47X7wpIjt\\nZIxuh9hCX4XUTTaMzGGSsLk=\\n-----END PRIVATE KEY-----\\n",\r\n  "client_email": "python-gsheet@earnest-coder-312212.iam.gserviceaccount.com",\r\n  "client_id": "114460034961749852195",\r\n  "auth_uri": "https://accounts.google.com/o/oauth2/auth",\r\n  "token_uri": "https://oauth2.googleapis.com/token",\r\n  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",\r\n  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/python-gsheet%40earnest-coder-312212.iam.gserviceaccount.com",\r\n  "universe_domain": "googleapis.com"\r\n}'; 3492)
[2023-10-22T16:36:29.988+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T16:36:30.008+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
