[2023-10-24T16:24:19.590+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_data_crawler.upload_to_db backfill__2023-10-09T10:00:00+00:00 [queued]>
[2023-10-24T16:24:19.599+0800] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_data_crawler.upload_to_db backfill__2023-10-09T10:00:00+00:00 [queued]>
[2023-10-24T16:24:19.600+0800] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-24T16:24:19.616+0800] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_to_db> on 2023-10-09 10:00:00+00:00
[2023-10-24T16:24:19.625+0800] {standard_task_runner.py:57} INFO - Started process 228 to run task
[2023-10-24T16:24:19.629+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stock_data_crawler', 'upload_to_db', 'backfill__2023-10-09T10:00:00+00:00', '--job-id', '207', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_crawler.py', '--cfg-path', '/tmp/tmp3p0t8gzb']
[2023-10-24T16:24:19.631+0800] {standard_task_runner.py:85} INFO - Job 207: Subtask upload_to_db
[2023-10-24T16:24:19.669+0800] {task_command.py:416} INFO - Running <TaskInstance: stock_data_crawler.upload_to_db backfill__2023-10-09T10:00:00+00:00 [running]> on host d9341a59eebf
[2023-10-24T16:24:19.723+0800] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='joshua881117@gmail.com' AIRFLOW_CTX_DAG_OWNER='Joshua Lin' AIRFLOW_CTX_DAG_ID='stock_data_crawler' AIRFLOW_CTX_TASK_ID='upload_to_db' AIRFLOW_CTX_EXECUTION_DATE='2023-10-09T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2023-10-09T10:00:00+00:00'
[2023-10-24T16:24:19.727+0800] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stock_data_crawler.py", line 61, in upload_data
    df = pd.read_csv(file_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/stock_data_2023-10-24.csv'
[2023-10-24T16:24:19.732+0800] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_data_crawler, task_id=upload_to_db, execution_date=20231009T100000, start_date=20231024T082419, end_date=20231024T082419
[2023-10-24T16:24:19.755+0800] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-10-24T16:24:19.755+0800] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-24T16:24:21.015+0800] {email.py:281} INFO - Sent an alert email to ['joshua881117@gmail.com']
[2023-10-24T16:24:22.260+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 207 for task upload_to_db ([Errno 2] No such file or directory: '/opt/airflow/dags/data/stock_data_2023-10-24.csv'; 228)
[2023-10-24T16:24:22.342+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-24T16:24:22.379+0800] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
