[2023-10-26T18:13:15.583+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_minio_v2.sensor_minio_s3 manual__2023-10-26T10:12:37.985672+00:00 [queued]>
[2023-10-26T18:13:15.594+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_minio_v2.sensor_minio_s3 manual__2023-10-26T10:12:37.985672+00:00 [queued]>
[2023-10-26T18:13:15.595+0800] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-10-26T18:13:15.604+0800] {taskinstance.py:1380} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2023-10-26 10:12:37.985672+00:00
[2023-10-26T18:13:15.608+0800] {standard_task_runner.py:57} INFO - Started process 1545 to run task
[2023-10-26T18:13:15.612+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_minio_v2', 'sensor_minio_s3', 'manual__2023-10-26T10:12:37.985672+00:00', '--job-id', '641', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_minio.py', '--cfg-path', '/tmp/tmpx9248u00']
[2023-10-26T18:13:15.615+0800] {standard_task_runner.py:85} INFO - Job 641: Subtask sensor_minio_s3
[2023-10-26T18:13:15.653+0800] {task_command.py:415} INFO - Running <TaskInstance: dag_with_minio_v2.sensor_minio_s3 manual__2023-10-26T10:12:37.985672+00:00 [running]> on host 26a4c5bc8d30
[2023-10-26T18:13:15.707+0800] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='joshua881117@gmail.com' AIRFLOW_CTX_DAG_OWNER='Joshua Lin' AIRFLOW_CTX_DAG_ID='dag_with_minio_v2' AIRFLOW_CTX_TASK_ID='sensor_minio_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-10-26T10:12:37.985672+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-26T10:12:37.985672+00:00'
[2023-10-26T18:13:15.708+0800] {s3.py:106} INFO - Poking for key : s3://***/result.csv
[2023-10-26T18:13:15.714+0800] {base.py:73} INFO - Using connection ID 'minio_conn' for task execution.
[2023-10-26T18:13:15.714+0800] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2023-10-26T18:13:21.485+0800] {s3.py:106} INFO - Poking for key : s3://***/result.csv
[2023-10-26T18:13:26.541+0800] {s3.py:106} INFO - Poking for key : s3://***/result.csv
[2023-10-26T18:13:31.606+0800] {s3.py:106} INFO - Poking for key : s3://***/result.csv
[2023-10-26T18:13:36.680+0800] {s3.py:106} INFO - Poking for key : s3://***/result.csv
[2023-10-26T18:13:41.715+0800] {s3.py:106} INFO - Poking for key : s3://***/result.csv
[2023-10-26T18:13:46.746+0800] {s3.py:106} INFO - Poking for key : s3://***/result.csv
[2023-10-26T18:13:46.797+0800] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 144, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 31.0855342639843 seconds exceeds the specified timeout of 30.0.
[2023-10-26T18:13:46.859+0800] {taskinstance.py:1398} INFO - Immediate failure requested. Marking task as FAILED. dag_id=dag_with_minio_v2, task_id=sensor_minio_s3, execution_date=20231026T101237, start_date=20231026T101315, end_date=20231026T101346
[2023-10-26T18:13:46.883+0800] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-10-26T18:13:46.884+0800] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-26T18:13:48.443+0800] {email.py:282} INFO - Sent an alert email to ['joshua881117@gmail.com']
[2023-10-26T18:13:49.796+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 641 for task sensor_minio_s3 (Sensor has timed out; run duration of 31.0855342639843 seconds exceeds the specified timeout of 30.0.; 1545)
[2023-10-26T18:13:49.833+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-26T18:13:49.880+0800] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
