[2023-10-27T18:37:31.888+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_notification.get_stock_price scheduled__2023-10-25T18:00:00+00:00 [queued]>
[2023-10-27T18:37:31.893+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_notification.get_stock_price scheduled__2023-10-25T18:00:00+00:00 [queued]>
[2023-10-27T18:37:31.893+0800] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-10-27T18:37:31.901+0800] {taskinstance.py:1380} INFO - Executing <Task(BranchPythonOperator): get_stock_price> on 2023-10-25 18:00:00+00:00
[2023-10-27T18:37:31.906+0800] {standard_task_runner.py:57} INFO - Started process 218 to run task
[2023-10-27T18:37:31.909+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'stock_notification', 'get_stock_price', 'scheduled__2023-10-25T18:00:00+00:00', '--job-id', '668', '--raw', '--subdir', 'DAGS_FOLDER/stock_notification.py', '--cfg-path', '/tmp/tmpnx_gzuk_']
[2023-10-27T18:37:31.910+0800] {standard_task_runner.py:85} INFO - Job 668: Subtask get_stock_price
[2023-10-27T18:37:31.933+0800] {task_command.py:415} INFO - Running <TaskInstance: stock_notification.get_stock_price scheduled__2023-10-25T18:00:00+00:00 [running]> on host 9a28c8ad9082
[2023-10-27T18:37:31.977+0800] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='joshua881117@gmail.com' AIRFLOW_CTX_DAG_OWNER='Joshua Lin' AIRFLOW_CTX_DAG_ID='stock_notification' AIRFLOW_CTX_TASK_ID='get_stock_price' AIRFLOW_CTX_EXECUTION_DATE='2023-10-25T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-25T18:00:00+00:00'
[2023-10-27T18:37:39.401+0800] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 226, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stock_notification.py", line 39, in get_stock_data
    df.to_csv(file_path, index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/opt/***/dags/data'
[2023-10-27T18:37:39.407+0800] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_notification, task_id=get_stock_price, execution_date=20231025T180000, start_date=20231027T103731, end_date=20231027T103739
[2023-10-27T18:37:39.418+0800] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-10-27T18:37:39.419+0800] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-27T18:37:40.287+0800] {email.py:282} INFO - Sent an alert email to ['joshua881117@gmail.com']
[2023-10-27T18:37:41.428+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 668 for task get_stock_price (Cannot save file into a non-existent directory: '/opt/***/dags/data'; 218)
[2023-10-27T18:37:41.481+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-27T18:37:41.518+0800] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
